### ISSUE TITLE
Replica sets in mongodb > 2.0

### ISSUE THREAD

**Issue by mnology** [afloyd/mongo-migrate#45]
Using latest mongodb native(2.0.49) the function for defining Replica set servers seems to have been changed to ReplSet, and is no longer ReplSetServers

```
node_modules/mongodb-migrate/lib/db.js:22
   return new mongodb.ReplSetServers(replServers);
          ^
TypeError: undefined is not a function
    at getReplicaSetServers (...node_modules/mongodb-migrate/lib/db.js:22:11)
    at Object.getConnection (...node_modules/mongodb-migrate/lib/db.js:31:11)
    at performMigration (...node_modules/mongodb-migrate/index.js:267:6)
    at commands.up (...node_modules/mongodb-migrate/index.js:203:4)
    at runMongoMigrate (...node_modules/mongodb-migrate/index.js:319:10)
    at Object.<anonymous> (...node_modules/mongodb-migrate/index.js:375:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by afloyd** [comment]
I don't have any replication sets to test with, but if you submit a pull
request I'll merge it

**Comment by beholderrk** [comment]
This [PR](https://github.com/afloyd/mongo-migrate/pull/46) can allow to avoid problem with ReplSet

**Comment by akoskm** [comment]
Any chance for this to be merged?

**Comment by afloyd** [comment]
See #46, the PR had conflicts so I merged as best as possible...
